name: Python application
on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Set version variable
        id: vars
        shell: bash
        run: echo "TAG_NAME=v$(date -u +%Y%m%d)" >> $GITHUB_ENV

      - name: Build exe with PyInstaller
        run: pyinstaller --clean --noconfirm better-mute.spec

      - name: Get executable filename
        id: exe
        shell: bash
        run: |
          exe_file=$(find dist -name "*.exe" | head -n1)
          echo "EXE_PATH=$exe_file" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


